version: 2.1
jobs:
  build-gsi:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install git
           git clone --recurse-submodules https://github.com/kmou424/ErfanGSIs.git --depth=1
           cd ErfanGSIs
           git clone https://github.com/kmou424/auto_build_gsi build_scripts
           source build_scripts/build.sh
      - store_artifacts:
          path: /tmp/output
workflows:
  version: 2.1
  cooking:
    jobs:
      - build-gsi
